import type { CapsuleDef, CapsuleKind, ParamDef, SocketDef } from './types';

const toggle = (id: string, label: string, def = false, help?: string): ParamDef =>
  ({ id, label, kind: 'toggle', default: def, help });
const text = (id: string, label: string, def = '', help?: string): ParamDef =>
  ({ id, label, kind: 'text', default: def, help });
const textarea = (id: string, label: string, def = '', help?: string): ParamDef =>
  ({ id, label, kind: 'textarea', default: def, help });
const num = (id: string, label: string, min: number, max: number, step: number, def: number, help?: string): ParamDef =>
  ({ id, label, kind: 'number', min, max, step, default: def, help });
const select = (id: string, label: string, options: { value: string; label: string }[], def: string, help?: string): ParamDef =>
  ({ id, label, kind: 'select', options, default: def, help });

const s = (id: string, label: string, type: SocketDef['type']): SocketDef => ({ id, label, type });

/**
 * Registry of graph capsules. The first ten are LumenDeck's executable core
 * recipe; the rest are ComfyUI-style building blocks for planning, layout,
 * interoperability, and future backend expansion.
 */
export const CAPSULES: Record<CapsuleKind, CapsuleDef> = {
  prompt: {
    kind: 'prompt',
    category: 'core',
    title: 'Prompt',
    accent: 'var(--cap-prompt)',
    description: 'Positive and negative text conditioning.',
    inputs: [],
    outputs: [s('conditioning', 'Conditioning', 'conditioning')],
    params: [
      textarea('positive', 'Prompt', 'a luminous deck of glowing cards floating over a midnight ocean, volumetric light, ultra detailed', 'Describe the image you want.'),
      textarea('negative', 'Negative prompt', 'blurry, low quality, watermark', 'What to avoid.'),
    ],
  },
  model: {
    kind: 'model',
    category: 'core',
    title: 'Model',
    accent: 'var(--cap-model)',
    description: 'Base checkpoint that defines the look and capability.',
    inputs: [],
    outputs: [s('model', 'Model', 'model')],
    params: [
      select('assetId', 'Checkpoint', [], ''),
      select('precision', 'Precision', [
        { value: 'auto', label: 'Auto' },
        { value: 'fp16', label: 'FP16' },
        { value: 'bf16', label: 'BF16' },
        { value: 'fp32', label: 'FP32' },
      ], 'auto'),
      num('clipSkip', 'CLIP skip', 0, 12, 1, 0),
      text('vae', 'VAE override', '', 'Optional VAE file or backend alias.'),
    ],
  },
  checkpointLoader: {
    kind: 'checkpointLoader',
    category: 'loaders',
    title: 'Checkpoint Loader',
    accent: 'var(--cap-model)',
    description: 'Loads a checkpoint and exposes model, CLIP, and VAE sockets.',
    inputs: [],
    outputs: [s('model', 'Model', 'model'), s('clip', 'CLIP', 'clip'), s('vae', 'VAE', 'vae')],
    params: [
      text('checkpoint', 'Checkpoint name', 'model.safetensors'),
      select('precision', 'Precision', [
        { value: 'auto', label: 'Auto' },
        { value: 'fp16', label: 'FP16' },
        { value: 'bf16', label: 'BF16' },
        { value: 'fp32', label: 'FP32' },
      ], 'auto'),
    ],
  },
  clipTextEncode: {
    kind: 'clipTextEncode',
    category: 'conditioning',
    title: 'CLIP Text Encode',
    accent: 'var(--cap-conditioning)',
    description: 'Encodes text using an explicit CLIP input.',
    inputs: [s('clip', 'CLIP', 'clip')],
    outputs: [s('conditioning', 'Conditioning', 'conditioning')],
    params: [textarea('text', 'Text', 'cinematic lighting, detailed, sharp focus')],
  },
  clipSetLastLayer: {
    kind: 'clipSetLastLayer',
    category: 'conditioning',
    title: 'CLIP Set Last Layer',
    accent: 'var(--cap-conditioning)',
    description: 'Adjusts CLIP skip / last-layer behavior.',
    inputs: [s('clip', 'CLIP', 'clip')],
    outputs: [s('clip', 'CLIP', 'clip')],
    params: [num('stopAtClipLayer', 'Stop at layer', -12, 0, 1, -2)],
  },
  conditioningCombine: {
    kind: 'conditioningCombine',
    category: 'conditioning',
    title: 'Conditioning Combine',
    accent: 'var(--cap-conditioning)',
    description: 'Merges two conditioning streams.',
    inputs: [s('a', 'A', 'conditioning'), s('b', 'B', 'conditioning')],
    outputs: [s('conditioning', 'Conditioning', 'conditioning')],
    params: [],
  },
  conditioningAverage: {
    kind: 'conditioningAverage',
    category: 'conditioning',
    title: 'Conditioning Average',
    accent: 'var(--cap-conditioning)',
    description: 'Blends two prompts by weight.',
    inputs: [s('a', 'A', 'conditioning'), s('b', 'B', 'conditioning')],
    outputs: [s('conditioning', 'Conditioning', 'conditioning')],
    params: [num('strength', 'Strength', 0, 1, 0.01, 0.5)],
  },
  conditioningSetArea: {
    kind: 'conditioningSetArea',
    category: 'conditioning',
    title: 'Conditioning Set Area',
    accent: 'var(--cap-conditioning)',
    description: 'Limits conditioning to a rectangular canvas region.',
    inputs: [s('conditioning', 'Conditioning', 'conditioning')],
    outputs: [s('conditioning', 'Conditioning', 'conditioning')],
    params: [
      num('x', 'X', 0, 8192, 8, 0),
      num('y', 'Y', 0, 8192, 8, 0),
      num('width', 'Width', 8, 8192, 8, 512),
      num('height', 'Height', 8, 8192, 8, 512),
      num('strength', 'Strength', 0, 1, 0.01, 1),
    ],
  },
  loraLoader: {
    kind: 'loraLoader',
    category: 'loaders',
    title: 'LoRA Loader',
    accent: 'var(--cap-lora)',
    description: 'Applies a LoRA to model and CLIP streams.',
    inputs: [s('model', 'Model', 'model'), s('clip', 'CLIP', 'clip')],
    outputs: [s('model', 'Model', 'model'), s('clip', 'CLIP', 'clip')],
    params: [
      text('loraName', 'LoRA name', 'style.safetensors'),
      num('modelStrength', 'Model strength', -2, 2, 0.05, 1),
      num('clipStrength', 'CLIP strength', -2, 2, 0.05, 1),
    ],
  },
  loraRack: {
    kind: 'loraRack',
    category: 'core',
    title: 'LoRA Rack',
    accent: 'var(--cap-lora)',
    description: 'Stack style/subject adapters on top of the base model.',
    inputs: [s('model_in', 'Model', 'model')],
    outputs: [s('model_out', 'Model + LoRAs', 'lora_stack')],
    params: [{ id: 'slots', label: 'LoRA slots', kind: 'text', default: [] as unknown }],
  },
  vaeLoader: {
    kind: 'vaeLoader',
    category: 'loaders',
    title: 'VAE Loader',
    accent: 'var(--cap-latent)',
    description: 'Loads a VAE for encode/decode operations.',
    inputs: [],
    outputs: [s('vae', 'VAE', 'vae')],
    params: [text('vaeName', 'VAE name', 'vae.safetensors')],
  },
  emptyLatent: {
    kind: 'emptyLatent',
    category: 'latent',
    title: 'Empty Latent Image',
    accent: 'var(--cap-latent)',
    description: 'Creates a blank latent tensor at a target size.',
    inputs: [],
    outputs: [s('latent', 'Latent', 'latent')],
    params: [
      num('width', 'Width', 64, 8192, 8, 1024),
      num('height', 'Height', 64, 8192, 8, 1024),
      num('batch', 'Batch', 1, 16, 1, 1),
    ],
  },
  latentNoise: {
    kind: 'latentNoise',
    category: 'latent',
    title: 'Latent Noise',
    accent: 'var(--cap-latent)',
    description: 'Adds controllable noise to a latent.',
    inputs: [s('latent', 'Latent', 'latent')],
    outputs: [s('latent', 'Latent', 'latent'), s('noise', 'Noise', 'noise')],
    params: [num('strength', 'Strength', 0, 2, 0.01, 1), { id: 'seed', label: 'Seed', kind: 'seed', default: -1 }],
  },
  latentUpscale: {
    kind: 'latentUpscale',
    category: 'latent',
    title: 'Latent Upscale',
    accent: 'var(--cap-latent)',
    description: 'Upscales a latent before another sampling pass.',
    inputs: [s('latent', 'Latent', 'latent')],
    outputs: [s('latent', 'Latent', 'latent')],
    params: [
      num('width', 'Width', 64, 8192, 8, 1536),
      num('height', 'Height', 64, 8192, 8, 1536),
      select('method', 'Method', [
        { value: 'nearest-exact', label: 'Nearest exact' },
        { value: 'bilinear', label: 'Bilinear' },
        { value: 'bicubic', label: 'Bicubic' },
        { value: 'area', label: 'Area' },
      ], 'bicubic'),
    ],
  },
  latentCrop: {
    kind: 'latentCrop',
    category: 'latent',
    title: 'Latent Crop',
    accent: 'var(--cap-latent)',
    description: 'Crops latent space without decoding.',
    inputs: [s('latent', 'Latent', 'latent')],
    outputs: [s('latent', 'Latent', 'latent')],
    params: [num('x', 'X', 0, 8192, 8, 0), num('y', 'Y', 0, 8192, 8, 0), num('width', 'Width', 8, 8192, 8, 512), num('height', 'Height', 8, 8192, 8, 512)],
  },
  latentComposite: {
    kind: 'latentComposite',
    category: 'latent',
    title: 'Latent Composite',
    accent: 'var(--cap-latent)',
    description: 'Composites a source latent over a destination latent.',
    inputs: [s('destination', 'Destination', 'latent'), s('source', 'Source', 'latent'), s('mask', 'Mask', 'mask')],
    outputs: [s('latent', 'Latent', 'latent')],
    params: [num('x', 'X', 0, 8192, 8, 0), num('y', 'Y', 0, 8192, 8, 0), toggle('feather', 'Feather mask', true)],
  },
  vaeEncode: {
    kind: 'vaeEncode',
    category: 'latent',
    title: 'VAE Encode',
    accent: 'var(--cap-latent)',
    description: 'Encodes an image into latent space.',
    inputs: [s('image', 'Image', 'image'), s('vae', 'VAE', 'vae')],
    outputs: [s('latent', 'Latent', 'latent')],
    params: [],
  },
  vaeDecode: {
    kind: 'vaeDecode',
    category: 'latent',
    title: 'VAE Decode',
    accent: 'var(--cap-latent)',
    description: 'Decodes latent space back to image pixels.',
    inputs: [s('latent', 'Latent', 'latent'), s('vae', 'VAE', 'vae')],
    outputs: [s('image', 'Image', 'image')],
    params: [],
  },
  control: {
    kind: 'control',
    category: 'core',
    title: 'Control',
    accent: 'var(--cap-control)',
    description: 'Optional structural guidance (pose, depth, edges).',
    inputs: [],
    outputs: [s('control', 'Control', 'control')],
    params: [
      toggle('enabled', 'Enabled', false),
      select('preprocessor', 'Preprocessor', [
        { value: 'none', label: 'None' },
        { value: 'canny', label: 'Canny' },
        { value: 'depth_midas', label: 'Depth MiDaS' },
        { value: 'openpose', label: 'OpenPose' },
        { value: 'lineart', label: 'Lineart' },
        { value: 'tile', label: 'Tile' },
      ], 'none'),
      select('mode', 'Mode', [
        { value: 'none', label: 'None' },
        { value: 'canny', label: 'Canny edges' },
        { value: 'depth', label: 'Depth' },
        { value: 'pose', label: 'Pose' },
      ], 'none'),
      num('strength', 'Strength', 0, 2, 0.05, 1),
      num('startPercent', 'Start %', 0, 1, 0.05, 0),
      num('endPercent', 'End %', 0, 1, 0.05, 1),
    ],
  },
  controlNetLoader: {
    kind: 'controlNetLoader',
    category: 'control',
    title: 'ControlNet Loader',
    accent: 'var(--cap-control)',
    description: 'Loads a ControlNet model.',
    inputs: [],
    outputs: [s('control', 'ControlNet', 'control')],
    params: [text('controlNetName', 'ControlNet name', 'controlnet.safetensors')],
  },
  controlNetApply: {
    kind: 'controlNetApply',
    category: 'control',
    title: 'Apply ControlNet',
    accent: 'var(--cap-control)',
    description: 'Applies a ControlNet image to conditioning.',
    inputs: [s('conditioning', 'Conditioning', 'conditioning'), s('control', 'ControlNet', 'control'), s('image', 'Image', 'image')],
    outputs: [s('conditioning', 'Conditioning', 'conditioning')],
    params: [num('strength', 'Strength', 0, 2, 0.05, 1), num('startPercent', 'Start %', 0, 1, 0.05, 0), num('endPercent', 'End %', 0, 1, 0.05, 1)],
  },
  cannyPreprocessor: {
    kind: 'cannyPreprocessor',
    category: 'control',
    title: 'Canny Preprocessor',
    accent: 'var(--cap-control)',
    description: 'Extracts edge guidance from an image.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('image', 'Edges', 'image')],
    params: [num('lowThreshold', 'Low threshold', 0, 255, 1, 100), num('highThreshold', 'High threshold', 0, 255, 1, 200)],
  },
  depthPreprocessor: {
    kind: 'depthPreprocessor',
    category: 'control',
    title: 'Depth Preprocessor',
    accent: 'var(--cap-control)',
    description: 'Estimates depth guidance from an image.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('image', 'Depth', 'image')],
    params: [select('model', 'Estimator', [{ value: 'midas', label: 'MiDaS' }, { value: 'zoe', label: 'ZoeDepth' }, { value: 'leres', label: 'LeReS' }], 'midas')],
  },
  posePreprocessor: {
    kind: 'posePreprocessor',
    category: 'control',
    title: 'Pose Preprocessor',
    accent: 'var(--cap-control)',
    description: 'Extracts pose guidance from an image.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('image', 'Pose', 'image')],
    params: [toggle('hands', 'Hands', true), toggle('face', 'Face', true), toggle('body', 'Body', true)],
  },
  imageLoader: {
    kind: 'imageLoader',
    category: 'loaders',
    title: 'Load Image',
    accent: 'var(--cap-image)',
    description: 'Loads an image for img2img, masks, or ControlNet.',
    inputs: [],
    outputs: [s('image', 'Image', 'image'), s('mask', 'Mask', 'mask')],
    params: [text('path', 'Image path', ''), toggle('alphaToMask', 'Alpha to mask', true)],
  },
  imageScale: {
    kind: 'imageScale',
    category: 'image',
    title: 'Image Scale',
    accent: 'var(--cap-image)',
    description: 'Scales an image to exact dimensions.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('image', 'Image', 'image')],
    params: [num('width', 'Width', 1, 8192, 1, 1024), num('height', 'Height', 1, 8192, 1, 1024), select('method', 'Method', [{ value: 'lanczos', label: 'Lanczos' }, { value: 'bicubic', label: 'Bicubic' }, { value: 'nearest', label: 'Nearest' }], 'lanczos')],
  },
  imageCrop: {
    kind: 'imageCrop',
    category: 'image',
    title: 'Image Crop',
    accent: 'var(--cap-image)',
    description: 'Crops an image region.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('image', 'Image', 'image')],
    params: [num('x', 'X', 0, 8192, 1, 0), num('y', 'Y', 0, 8192, 1, 0), num('width', 'Width', 1, 8192, 1, 512), num('height', 'Height', 1, 8192, 1, 512)],
  },
  imageBlend: {
    kind: 'imageBlend',
    category: 'image',
    title: 'Image Blend',
    accent: 'var(--cap-image)',
    description: 'Blends two images with a mode and factor.',
    inputs: [s('a', 'A', 'image'), s('b', 'B', 'image'), s('mask', 'Mask', 'mask')],
    outputs: [s('image', 'Image', 'image')],
    params: [select('mode', 'Mode', [{ value: 'normal', label: 'Normal' }, { value: 'multiply', label: 'Multiply' }, { value: 'screen', label: 'Screen' }, { value: 'overlay', label: 'Overlay' }], 'normal'), num('factor', 'Factor', 0, 1, 0.01, 0.5)],
  },
  imageSharpen: {
    kind: 'imageSharpen',
    category: 'image',
    title: 'Image Sharpen',
    accent: 'var(--cap-image)',
    description: 'Sharpens image detail after sampling.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('image', 'Image', 'image')],
    params: [num('amount', 'Amount', 0, 2, 0.05, 0.45), num('radius', 'Radius', 0, 8, 0.1, 1)],
  },
  imageColorCorrect: {
    kind: 'imageColorCorrect',
    category: 'image',
    title: 'Color Correct',
    accent: 'var(--cap-image)',
    description: 'Adjusts brightness, contrast, saturation, and gamma.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('image', 'Image', 'image')],
    params: [num('brightness', 'Brightness', -1, 1, 0.01, 0), num('contrast', 'Contrast', -1, 1, 0.01, 0), num('saturation', 'Saturation', -1, 1, 0.01, 0), num('gamma', 'Gamma', 0.1, 4, 0.05, 1)],
  },
  imageToMask: {
    kind: 'imageToMask',
    category: 'mask',
    title: 'Image To Mask',
    accent: 'var(--cap-mask)',
    description: 'Converts an image channel into a mask.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('mask', 'Mask', 'mask')],
    params: [select('channel', 'Channel', [{ value: 'alpha', label: 'Alpha' }, { value: 'red', label: 'Red' }, { value: 'green', label: 'Green' }, { value: 'blue', label: 'Blue' }, { value: 'luma', label: 'Luma' }], 'alpha')],
  },
  maskBlur: {
    kind: 'maskBlur',
    category: 'mask',
    title: 'Mask Blur',
    accent: 'var(--cap-mask)',
    description: 'Softens a mask edge.',
    inputs: [s('mask', 'Mask', 'mask')],
    outputs: [s('mask', 'Mask', 'mask')],
    params: [num('radius', 'Radius', 0, 256, 1, 16)],
  },
  maskGrow: {
    kind: 'maskGrow',
    category: 'mask',
    title: 'Mask Grow',
    accent: 'var(--cap-mask)',
    description: 'Expands or contracts a mask.',
    inputs: [s('mask', 'Mask', 'mask')],
    outputs: [s('mask', 'Mask', 'mask')],
    params: [num('pixels', 'Pixels', -256, 256, 1, 8), toggle('tapered', 'Tapered corners', true)],
  },
  maskComposite: {
    kind: 'maskComposite',
    category: 'mask',
    title: 'Mask Composite',
    accent: 'var(--cap-mask)',
    description: 'Combines two masks.',
    inputs: [s('a', 'A', 'mask'), s('b', 'B', 'mask')],
    outputs: [s('mask', 'Mask', 'mask')],
    params: [select('operation', 'Operation', [{ value: 'add', label: 'Add' }, { value: 'subtract', label: 'Subtract' }, { value: 'multiply', label: 'Multiply' }, { value: 'max', label: 'Max' }], 'add')],
  },
  sampler: {
    kind: 'sampler',
    category: 'core',
    title: 'Sampler',
    accent: 'var(--cap-sampler)',
    description: 'How the image is denoised: algorithm, steps, guidance, seed.',
    inputs: [s('conditioning', 'Conditioning', 'conditioning'), s('model', 'Model', 'lora_stack'), s('control', 'Control', 'control'), s('latent', 'Canvas', 'latent')],
    outputs: [s('image', 'Image', 'image')],
    params: [
      select('sampler', 'Sampler', [
        { value: 'euler', label: 'Euler' },
        { value: 'euler_a', label: 'Euler Ancestral' },
        { value: 'dpmpp_2m', label: 'DPM++ 2M' },
        { value: 'dpmpp_2m_sde', label: 'DPM++ 2M SDE' },
        { value: 'dpmpp_3m_sde', label: 'DPM++ 3M SDE' },
        { value: 'ddim', label: 'DDIM' },
        { value: 'uni_pc', label: 'UniPC' },
      ], 'euler_a'),
      select('scheduler', 'Scheduler', [
        { value: 'normal', label: 'Normal' },
        { value: 'karras', label: 'Karras' },
        { value: 'exponential', label: 'Exponential' },
        { value: 'sgm_uniform', label: 'SGM uniform' },
        { value: 'simple', label: 'Simple' },
      ], 'karras'),
      num('steps', 'Steps', 1, 150, 1, 28),
      num('cfg', 'Guidance (CFG)', 1, 30, 0.5, 7),
      num('denoise', 'Denoise', 0, 1, 0.01, 1),
      num('cfgRescale', 'CFG rescale', 0, 1, 0.05, 0),
      { id: 'seed', label: 'Seed', kind: 'seed', default: 1337, help: '-1 rolls a random seed per render.' },
    ],
  },
  samplerAdvanced: {
    kind: 'samplerAdvanced',
    category: 'sampling',
    title: 'KSampler Advanced',
    accent: 'var(--cap-sampler)',
    description: 'Advanced sampling with separate noise and latent inputs.',
    inputs: [s('model', 'Model', 'model'), s('positive', 'Positive', 'conditioning'), s('negative', 'Negative', 'conditioning'), s('latent', 'Latent', 'latent'), s('noise', 'Noise', 'noise')],
    outputs: [s('latent', 'Latent', 'latent')],
    params: [toggle('addNoise', 'Add noise', true), num('startStep', 'Start step', 0, 150, 1, 0), num('endStep', 'End step', 1, 150, 1, 28), toggle('returnWithLeftoverNoise', 'Return leftover noise', false)],
  },
  refinerSampler: {
    kind: 'refinerSampler',
    category: 'sampling',
    title: 'Refiner Sampler',
    accent: 'var(--cap-sampler)',
    description: 'Second-pass sampler for SDXL refiner-style workflows.',
    inputs: [s('model', 'Refiner model', 'model'), s('conditioning', 'Conditioning', 'conditioning'), s('latent', 'Latent', 'latent')],
    outputs: [s('latent', 'Latent', 'latent')],
    params: [num('switchAt', 'Switch at %', 0, 1, 0.01, 0.8), num('steps', 'Steps', 1, 80, 1, 12), num('cfg', 'CFG', 0, 20, 0.5, 5)],
  },
  hiresFix: {
    kind: 'hiresFix',
    category: 'sampling',
    title: 'Hires Fix',
    accent: 'var(--cap-sampler)',
    description: 'Upscale and denoise pass for high-resolution output.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('image', 'Image', 'image')],
    params: [num('scale', 'Scale', 1, 4, 0.05, 1.5), num('denoise', 'Denoise', 0, 1, 0.01, 0.35), num('steps', 'Steps', 1, 80, 1, 14)],
  },
  upscaleModelLoader: {
    kind: 'upscaleModelLoader',
    category: 'loaders',
    title: 'Upscale Model Loader',
    accent: 'var(--cap-image)',
    description: 'Loads an ESRGAN/RealESRGAN-style upscale model.',
    inputs: [],
    outputs: [s('upscale_model', 'Upscale model', 'upscale_model')],
    params: [text('modelName', 'Model name', '4x-UltraSharp.pth')],
  },
  imageUpscaleWithModel: {
    kind: 'imageUpscaleWithModel',
    category: 'image',
    title: 'Upscale Image By Model',
    accent: 'var(--cap-image)',
    description: 'Upscales an image with a loaded upscale model.',
    inputs: [s('image', 'Image', 'image'), s('upscale_model', 'Model', 'upscale_model')],
    outputs: [s('image', 'Image', 'image')],
    params: [toggle('tile', 'Tile', true), num('tileSize', 'Tile size', 64, 1024, 64, 512)],
  },
  faceDetailer: {
    kind: 'faceDetailer',
    category: 'image',
    title: 'Face Detailer',
    accent: 'var(--cap-image)',
    description: 'Detects faces and runs a focused detail pass.',
    inputs: [s('image', 'Image', 'image'), s('model', 'Model', 'model'), s('conditioning', 'Conditioning', 'conditioning')],
    outputs: [s('image', 'Image', 'image'), s('mask', 'Face mask', 'mask')],
    params: [num('confidence', 'Confidence', 0, 1, 0.01, 0.5), num('denoise', 'Denoise', 0, 1, 0.01, 0.35), num('padding', 'Padding', 0, 256, 1, 32)],
  },
  previewImage: {
    kind: 'previewImage',
    category: 'output',
    title: 'Preview Image',
    accent: 'var(--cap-export)',
    description: 'Shows an image while designing the graph.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('image', 'Image', 'image')],
    params: [toggle('pin', 'Pin preview', true), select('fit', 'Fit', [{ value: 'contain', label: 'Contain' }, { value: 'cover', label: 'Cover' }, { value: 'actual', label: 'Actual size' }], 'contain')],
  },
  video: {
    kind: 'video',
    category: 'core',
    title: 'Video',
    accent: 'var(--cap-video)',
    description: 'Animates the sampled image stream into a short loop.',
    inputs: [s('image', 'Image', 'image')],
    outputs: [s('media', 'Media', 'media')],
    params: [
      toggle('enabled', 'Render video', false),
      num('frameCount', 'Frames', 2, 96, 1, 16),
      num('fps', 'FPS', 1, 30, 1, 8),
      num('motionStrength', 'Motion strength', 0, 2, 0.05, 0.7),
      select('cameraMotion', 'Camera motion', [
        { value: 'orbit', label: 'Orbit' },
        { value: 'push', label: 'Push in' },
        { value: 'pan', label: 'Pan' },
        { value: 'pulse', label: 'Pulse' },
      ], 'orbit'),
      toggle('loop', 'Seamless loop', true),
    ],
  },
  frameInterpolator: {
    kind: 'frameInterpolator',
    category: 'video',
    title: 'Frame Interpolator',
    accent: 'var(--cap-video)',
    description: 'Plans a frame interpolation pass for smoother motion.',
    inputs: [s('media', 'Video', 'media')],
    outputs: [s('media', 'Video', 'media')],
    params: [select('method', 'Method', [{ value: 'rife', label: 'RIFE' }, { value: 'film', label: 'FILM' }, { value: 'blend', label: 'Blend' }], 'rife'), num('multiplier', 'Multiplier', 2, 8, 1, 2)],
  },
  canvas: {
    kind: 'canvas',
    category: 'core',
    title: 'Canvas',
    accent: 'var(--cap-canvas)',
    description: 'Output size and batch. Dimensions should be multiples of 8.',
    inputs: [],
    outputs: [s('latent', 'Latent', 'latent')],
    params: [
      num('width', 'Width', 64, 8192, 8, 1024),
      num('height', 'Height', 64, 8192, 8, 1024),
      num('batch', 'Batch size', 1, 16, 1, 1),
      toggle('tile', 'Tileable', false),
    ],
  },
  queue: {
    kind: 'queue',
    category: 'core',
    title: 'Queue',
    accent: 'var(--cap-queue)',
    description: 'Collects render jobs and dispatches them to the active backend.',
    inputs: [s('media', 'Media', 'media')],
    outputs: [s('media_out', 'Rendered', 'media')],
    params: [toggle('autoRun', 'Auto-run on change', false)],
  },
  note: {
    kind: 'note',
    category: 'utility',
    title: 'Note',
    accent: 'var(--cap-utility)',
    description: 'A graph note for documenting a recipe.',
    inputs: [],
    outputs: [],
    params: [textarea('body', 'Note', 'Describe this part of the graph.')],
  },
  reroute: {
    kind: 'reroute',
    category: 'utility',
    title: 'Reroute',
    accent: 'var(--cap-utility)',
    description: 'A typed pass-through to keep wires readable.',
    inputs: [s('in', 'In', 'media')],
    outputs: [s('out', 'Out', 'media')],
    params: [select('socketType', 'Display type', [{ value: 'media', label: 'Media' }, { value: 'image', label: 'Image' }, { value: 'latent', label: 'Latent' }, { value: 'conditioning', label: 'Conditioning' }], 'media')],
  },
  seed: {
    kind: 'seed',
    category: 'utility',
    title: 'Seed',
    accent: 'var(--cap-utility)',
    description: 'Reusable seed value.',
    inputs: [],
    outputs: [s('seed', 'Seed', 'number')],
    params: [{ id: 'value', label: 'Seed', kind: 'seed', default: -1 }],
  },
  math: {
    kind: 'math',
    category: 'utility',
    title: 'Math',
    accent: 'var(--cap-utility)',
    description: 'Scalar math helper for numeric graph parameters.',
    inputs: [s('a', 'A', 'number'), s('b', 'B', 'number')],
    outputs: [s('value', 'Value', 'number')],
    params: [select('operation', 'Operation', [{ value: 'add', label: 'Add' }, { value: 'subtract', label: 'Subtract' }, { value: 'multiply', label: 'Multiply' }, { value: 'divide', label: 'Divide' }], 'add')],
  },
  export: {
    kind: 'export',
    category: 'core',
    title: 'Export',
    accent: 'var(--cap-export)',
    description: 'Saves renders to the gallery and to disk.',
    inputs: [s('media', 'Media', 'media')],
    outputs: [s('manifest_out', 'Manifest', 'manifest')],
    params: [
      select('format', 'Format', [
        { value: 'png', label: 'PNG' },
        { value: 'webp', label: 'WebP' },
        { value: 'gif', label: 'GIF' },
      ], 'png'),
      toggle('embedManifest', 'Embed manifest', true),
    ],
  },
  manifest: {
    kind: 'manifest',
    category: 'core',
    title: 'Manifest',
    accent: 'var(--cap-manifest)',
    description: 'Reproducibility record: prompt, seed, models, LoRAs, graph.',
    inputs: [s('manifest_in', 'Manifest', 'manifest')],
    outputs: [],
    params: [
      toggle('includeGraph', 'Include graph snapshot', true),
      text('author', 'Author', ''),
    ],
  },
};

export const CAPSULE_KINDS = Object.keys(CAPSULES) as CapsuleKind[];

export const CAPSULE_CATEGORY_LABELS: Record<CapsuleDef['category'], string> = {
  core: 'Core',
  loaders: 'Loaders',
  conditioning: 'Conditioning',
  latent: 'Latent',
  control: 'Control',
  image: 'Image',
  mask: 'Mask',
  sampling: 'Sampling',
  video: 'Video',
  utility: 'Utility',
  output: 'Output',
};

export function capsuleDef(kind: CapsuleKind): CapsuleDef {
  return CAPSULES[kind];
}

export function defaultParams(kind: CapsuleKind): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const p of CAPSULES[kind].params) {
    out[p.id] = Array.isArray(p.default) ? [...(p.default as unknown[])] : p.default;
  }
  return out;
}
